def hello_from_bin() -> str: ...

class S3Storage:
    def list(self, path: str) -> list[str]: ...
    def does_file_exist(self, path: str) -> bool: ...
    def upload(self, local_path: str, remote_path: str) -> None: ...
    def delete(self, path: str) -> None: ...
    def download(self, remote_path: str, local_path: str) -> None: ...
    def byte_range_download(self, remote_path: str, local_path: str, num_threads: int) -> None: ...
