def hello_from_bin() -> str: ...

class S3ByteRangeDownloader:
    def __init__(self) -> None: ...
    def byte_range_download(self, remote_path: str, local_path: str, num_of_bytes: int, num_workers: int) -> None: ...
